select  first_name, LOWER(first_name) from employees;
select lower('asIODJOPDSDIKODS') from dual;
select * from employees where upper(first_name) = 'DAVID';
select first_name, initcap(first_name) from employees;
select * from employees where initcap(first_name) like '%en%';
select concat(salary*2, hire_date) from employees;
select sysdate from dual;
select concat('today is ', SYSDATE) from dual;
select first_name, length(first_name) as dlina from employees;
select length('zaur sak') from dual;
select salary, length(salary), hire_date, length(hire_date) from employees;
select country_name from countries where length(country_name)>8;
select country_name from countries order by length(country_name);

select LPAD('Zaur', 7, '#') from dual;
select RPAD('Zaur', 7, '#') from dual;
select first_name, LPAD(first_name, 25, '$'), RPAD(first_name, 25, '$') from employees;
select first_name, LPAD(first_name, 25, 'ABC') from employees;
select sysdate, lpad(sysdate,5,'!') from dual;
select RPAD(first_name,15,' ') || LPAD(salary,8,' ') from employees;
select TRIM(trailing 'q' from 'Zaurqqqqqqq') from dual;
select TRIM(leading 'q' from 'qqqqqqZaurqqqqqqq') from dual;
select TRIM('q' from 'qqqqqqZaqurqqqqqqq') from dual;
select TRIM(both 'q' from 'qqqqqqZqaurqqqqqqq') from dual;
select TRIM('     zaur l;adl;sal;dad                 ') from dual;
select * from employees where INSTR(job_id, 'PROG')=4;
select * from employees where INSTR(hire_date, '05')=4;
select * from employees where INSTR(salary, '2')=2;
select instr('zaur tregulov','u') from dual;
select instr('zaur tregulov','u',2) from dual;
select instr('zaur tregulov','u',2,2) from dual;